# ===================================================================
# Travel Blog Application - Modern Configuration (2025)
# ===================================================================

spring:
  application:
    name: travelblog
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Database Configuration
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mytour_travel?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # HikariCP connection pool settings (modern, high-performance)
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: TravelBlogHikariCP
      auto-commit: true
      connection-test-query: SELECT 1
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
    open-in-view: false
  
  # MVC Configuration
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true
    locale: en
    log-resolved-exception: false
    
  messages:
    basename: i18n/messages
    encoding: UTF-8
  
  # Web Resources
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/,classpath:/META-INF/resources/,file:src/main/webapp/
      cache:
        period: 3600
        cachecontrol:
          max-age: 3600
          cache-public: true
  
  # Servlet & Multipart Configuration
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB
      resolve-lazily: false
  
  # Cache Configuration (Caffeine)
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s
    cache-names:
      - destinations
      - packages
      - users
      - countries
      - categories
  
  # Jackson JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
        max-age: 1800
    jsp:
      init-parameters:
        development: true
        trim-spaces: true
        enable-pooling: false
  
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

# Actuator Configuration for Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers,caches
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.travelblog: DEBUG
    org.springframework.web: INFO
    org.springframework.web.servlet.view: DEBUG
    org.springframework.jdbc: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/travel-blog.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 1GB

# Application Custom Properties
application:
  name: MyTour Travel Blog
  version: 2.0.0
  description: Modern Travel Blog Application with Spring Boot
  api:
    version: v1
    base-path: /api/v1
  upload:
    max-file-size: 10MB
    allowed-extensions: jpg,jpeg,png,gif,webp
    upload-dir: ${java.io.tmpdir}/uploads
  security:
    jwt:
      secret: ${JWT_SECRET:your-secret-key-change-in-production}
      expiration: 86400000
  cache:
    default-ttl: 600



