# 生产环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytour_travel?useSSL=false&serverTimezone=Asia/Kuala_Lumpur&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: travelblog
    password: CHANGE_THIS_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  
server:
  port: 8080
  compression:
    enabled: true
  
logging:
  level:
    root: WARN
    com.example.travelblog: INFO
  file:
    name: logs/application.log
